# basic setting
title: Luan's Blogs
email: ntl080102@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Nguyen Thanh Luan
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  luannt0801

# Theme and plugin
theme: minima
plugins:
  - jekyll-feed

# build and directories
include: ["assets"]
exclude: ["README.md", "Gemfile", "Gemfile.lock"] 
destination: _site

# collection setting for pose
collections:
  posts:
    output: true
    permalink: /blogs/:title/
  portfolio:
    output: true
    permalink: /portfolio/:title/
  

# permalink for post
permalink: /:categories/:title/  # Định dạng đường dẫn bài viết
paginate_path: "/page:num/"  # Định dạng URL phân trang
